import Head from 'next/head'
import Homes from "../Components/Homes.jsx"
import Navbar from '../Components/Navbar.jsx'
export default function Home() {
  
  return (
    <div>
      <Head>
        <title>PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Homes/>
    </div>
  )
}
